### ISSUE TITLE
Parsing string with internal quotes 

### ISSUE THREAD

**Issue by shivchawla** [carlobaldassi/ArgParse.jl#36] opened 2016-11-18 18:15 UTC
Currently, it removes all quotes from  """this is a "complex" string"""" to "this is a complex string"

**Comment by carlobaldassi** [comment] 2020-01-21 19:22
I'm unable to reproduce this, and the issue is quite old. It might have been fixed in the meanwhile, so I'm closing it. If still relevant please comment and I'll reopen.

**Closed by carlobaldassi** 2020-01-21 19:22 UTC
