### ISSUE TITLE
Required argument listed as optional in arg table for command

### ISSUE THREAD

**Issue by cpaniaguam** [carlobaldassi/ArgParse.jl#122] opened 2023-05-10 15:35 UTC
```julia
julia> using ArgParse

julia> settings = ArgParseSettings();

julia> @add_arg_table! settings begin
           "cmd"
           action = :command
       end;

julia> @add_arg_table! settings["cmd"] begin
           "--opt1"
           required = true

           "--opt2"
           required = false
       end;

julia> parse_args(["cmd", "-h"], settings)
usage: <PROGRAM> cmd --opt1 OPT1 [--opt2 OPT2] [-h]

optional arguments:
  --opt1 OPT1
  --opt2 OPT2
  -h, --help   show this help message and exit
```

**Comment by carlobaldassi** [comment] 2023-05-10 16:39
This is not limited to commands; the issue is actually a duplicate of #108

**Closed by carlobaldassi** 2023-05-10 16:39 UTC
